# Generated by Django 4.2.1 on 2023-05-09 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='year',
            new_name='start_year',
        ),
        migrations.RemoveField(
            model_name='data',
            name='city',
        ),
    ]
