# Generated by Django 4.2.1 on 2023-05-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_rename_year_data_start_year_remove_data_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='topics',
            new_name='topic',
        ),
    ]
