# Generated by Django 4.2.1 on 2023-05-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0003_rename_topics_data_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
