# Generated by Django 4.2.1 on 2023-05-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0004_data_end_year_alter_data_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='end_year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
