# Generated by Django 4.2.1 on 2023-05-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0005_alter_data_end_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='intensity',
            field=models.FloatField(default=0),
        ),
    ]
