# Generated by Django 4.2.1 on 2023-05-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0006_alter_data_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='country',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
